### ISSUE TITLE
Failing to download packages

### ISSUE THREAD

**Issue by My-Random-Thoughts** [krglaws/MyLFS#3]
Getting to "Downloading packages to /mnt/lfs/sources...", sits there for a couple of minutes then returns me to the terminal prompt. No errors or warnings.

    Checking system dependencies... done.
    Creating image file... done.
    Creating basic directory layout... done.
    Downloading packages to /mnt/lfs/sources... 

Ubuntu 21.10

**Comment by krglaws** [comment]
Hmm weird. It might be that wget is quietly erroring out, since I have it using the `--quiet` option. Are there any files inside of the pkgs/ directory after you try running it? It caches the downloads there first before copying them onto the image file.

**Comment by My-Random-Thoughts** [comment]
Just downloaded and ran your code it again, it downloads 91 files:  8x .patch,  1x .pcf.gz,  3x .tar.bz2,  36x .tar.gz,  43x .tar.xz

I removed the --quiet option and all the files requested downloaded OK.
Just before the command prompt return, I get the following standard wget exit message:

    FINISHED --2022-04-06 08:10:54--
    Total wall clock time: 3m 45s
    Downloaded: 91 files, 449M in 2m 7s (3.54 MB/s)

**Comment by krglaws** [comment]
Ok thanks for that. It appears zlib has recently been updated to version 1.2.12 (as Bango88 pointed out) due to a security vulnerability. I've updated the listing in pkgs.sh, so this should be all fixed now.

**Comment by My-Random-Thoughts** [comment]
That worked, it's getter further now.  Thank you.
Might want to look at having a minimum version check and not exact.  You will be updating your version file constantly otherwise :)

**Comment by krglaws** [comment]
cool.

Also I recently made the version check step much less aggressive and brittle. Now you have to specify `--check` and it will output the minimum and maximum version requirements based on the listing in https://www.linuxfromscratch.org/lfs/view/stable/chapter02/hostreqs.html, as well as output the current versions on your system. However, it no longer compares the versions for you. We all have to use our EYEBALLS now... which is lame but it was too hard to get it to work 100% of the time.
